
* cl-libre-translate

** About
An easy to use Common Lisp binding for the Libre Translate service.

** Using

The easiest way to use this package is with the Docker configuration from [[https://github.com/LibreTranslate/LibreTranslate][Libre Translate]].

Clone the Libre Translate repo and start the service using:

#+begin_src shell
  ./run.sh --port 5001
#+end_src

Once the service has downloaded all of the language files, use the library to translate text:
#+begin_src lisp :results value
    (ql:quickload :cl-libre-translate)
    (use-package :st-json)
    (let ((result (lt:translate "This is a test!" :source "en" :target "es")))
      (st-json:getjso "translatedText" result))
#+end_src

#+RESULTS:
: ¡Esto es una prueba!

Parameters (and a config file) can be used to configure the Libre Translate server and API keys.
#+begin_src lisp :results value
  (ql:quickload :cl-libre-translate)
  (setf lt:*libre-translate-url* "https://libretranslate.com")
  (setf lt:*api-key* "Some API key")
  (let ((result (lt:translate "This is a test!" :source "en" :target "es")))
    (st-json:getjso "translatedText" result))
#+end_src

#+RESULTS:
: ¡Esto es una prueba!

** Config file
Config settings can also be read from a JSON file pointed to by the `lt:*config-file*` parameter.  The
default location is in the package directory.  Only "url" and "api_key" entries are supported, and both
are optional.  The default is to not use an API key and to connect to "http://localhost:5001".

*** Example Config
#+begin_src javascript
  {
      "api_key": "SomeAPI Key",
      "url": "https://localhost:5001"
  }
#+end_src

** API Keys Untested
So far I've only used this package against a local Docker service, without API keys.  I have little use
for the API keys right now, so I don't plan to test them.  If they are not working, please let me know,
and I'll try to fix them.  A PR fixing the problem would also be welcome.

** License
ISC

Copyright (c) 2024 Jeremiah LaRocco <jeremiah_larocco@fastmail.com>

